CREATE TABLE author(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE book(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE
);

INSERT INTO author (name)
SELECT 'Автор ' || i
FROM generate_series(1, 100) AS s(i);

INSERT INTO book (title, author_id)
SELECT 'Книга ' || j || ' автора ' || a.id,
       a.id
FROM author a
         CROSS JOIN generate_series(1, 10) AS g(j);