create table author(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

create table book(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE
);

INSERT INTO author (name) VALUES
       ('Лев Толстой'),
       ('Фёдор Достоевский'),
       ('Антон Чехов');


INSERT INTO book (title, author_id) VALUES
       ('Война и мир', 1),
       ('Анна Каренина', 1),
       ('Воскресение', 1),
       ('Крейцерова соната', 1),
       ('Смерть Ивана Ильича', 1),
       ('Детство', 1),
       ('Отрочество', 1),
       ('Юность', 1),
       ('Казаки', 1),
       ('Хаджи-Мурат', 1);


INSERT INTO book (title, author_id) VALUES
       ('Преступление и наказание', 2),
       ('Идиот', 2),
       ('Братья Карамазовы', 2),
       ('Бесы', 2),
       ('Подросток', 2),
       ('Игрок', 2),
       ('Униженные и оскорблённые', 2),
       ('Записки из подполья', 2),
       ('Белые ночи', 2),
       ('Неточка Незванова', 2);


INSERT INTO book (title, author_id) VALUES
       ('Вишнёвый сад', 3),
       ('Чайка', 3),
       ('Три сестры', 3),
       ('Дядя Ваня', 3),
       ('Палата №6', 3),
       ('Дама с собачкой', 3),
       ('Каштанка', 3),
       ('Ионыч', 3),
       ('Человек в футляре', 3),
       ('Степь', 3);